name: Build and Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    - name: Check Python version
      run: python --version
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Check Syntax 
      run: pycodestyle --statistics .
    - name: Run Migrations
      run: python manage.py migrate
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --ignore=E501 --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Test 
      run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v1
    
    - name: Build Docker image
      uses: actions/docker/cli@master
      with:
        args: "build . --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }}"

    - name: Authenticate into Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_AUTH }}

    - name: Configure Docker to use Google Cloud
      uses: actions/gcloud/cli@master
      with:
        args: "auth configure-docker --quiet"

    - name: Push image to GCR
      uses: actions/gcloud/cli@master
      with:
        entrypoint: sh
        args: -c "docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }}"

    - name: Install beta commands and deploy
      uses: actions/gcloud/cli@master
      with:
        args: "components install beta --quiet && gcloud beta run deploy ${{ secrets.GCP_APP_NAME }} --quiet --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }} --region us-east1 --project ${{ secrets.GCP_PROJECT }} --platform managed"
